server:
  port: 1000
eureka:
  instance:
    hostname: chnegp
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
spring:
  application:
    name: AIGOU_EUREKA