eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka #注册中心地址
  instance:
    prefer-ip-address: true  #显示ip
server:
  port: 2000
spring:
  application:
    name: AIGOU_PLAT